### ISSUE TITLE
Proposal: Make video optional and conduct interviews

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-selection#1]
# Proposal: Make video optional and conduct interviews

## WHY

In London, we require a video because we receive applications from more qualified candidates than we have previously had staff time to interview.

In Nazareth, we have required a video because we did so in London, and wanted to maintain a standard application process for international applicants. Local applicant numbers have been very low for the first two cohorts, and I think this may be a part of it. Furthermore, the Nazareth selection process has taken 3-4 hours for each of the first two cohorts. We spent this time discussing approximately 15-20 people. If we had offered each of them a 10-15 minute interview slot, either in-person or remote, with a 2-3 person panel, we could have answered many of the questions about candidates that we spent time debating.

Yesterday, we discussed the application process with the team in Gaza, and learned that the video requirement is discouraging many otherwise qualified and motivated people from applying - in particular women. They have staff time they can allocate to interviews, and we have decided there to make the video _optional_ and to plan short interviews with pretty much everyone who submits an otherwise complete application.

## WHAT

I propose that we make the video _optional_ for the next Nazareth programme and that we plan to interview all candidates (local and international) who complete the application. 

Given than numbers have historically been significantly smaller than in London, I am confident that we will have the human resources necessary to conduct this process professionally.

## HOW

Within the next year, I expect that we will build a proper site for FAC International, which will then link to sites for individual campuses, which will make it easier to communicate differences in selection processes.

In the meantime, we should EITHER update the application page to reflect that the video is optional for Nazareth applicants, and explain that we will be conducting interviews OR create a separate application page for the Nazareth programme, and modify the details there accordingly.

**Comment by des-des** [comment]
I think the problem here is that it will not scale. If for facn3 we have 30 applicants * 15 minutes * 3 interviewers = 1350 minutes = 22 hours (okay upper bound I know)..

It feel like a bit of a short term solution.

Also, how can we validate the idea that people are less likely to be put off by an interview than a video, before we put this idea into action?

**Comment by rebeccaradding** [comment]
@des-des you are right that it won't scale with volunteer labor. However, if we prioritize staff resources, we could manage a growth in the applicant pool. 

Gaza isn't Nazareth, but it was illuminating to understand just how off-putting that requirement is to otherwise very talented and motivated people. You are right to point out that my assumption is one we need to test - but after two cohorts and very few applicants, I think it is worth pivoting here. 

I suggest we form a committee/working group to discuss this and have a conversation about it as soon as possible, as any changes we do make will need to go into effect in time to inform the next candidate pool.

**Comment by sofer** [comment]
I am broadly in favour and would like us to consider introducing this in London on a trial basis for FAC11.

I would also like us to consider the possibility of:
- no cut-off point for applications;
- interviews on a rolling (possibly weekly) basis;
- conditional offers with a clear timetable for completion of prerequisites;

See also https://github.com/foundersandcoders/selection-committee/issues/49

**Comment by jsms90** [comment]
For history on this topic
+ search "interview" in [this issue](https://github.com/foundersandcoders/london-programme/issues/66) where they discussed having in-person interviews (now closed)
+ see [this issue](https://github.com/foundersandcoders/london-programme/issues/110)
+ and finally, the one that is still open called ["Interviews"](https://github.com/foundersandcoders/selection-committee/issues/3)

I suggest that we move this proposal to the Selection Committee repo ([see my thoughts on the split](https://github.com/foundersandcoders/selection-committee/issues/49#issuecomment-304499296)) & reference the "Interviews" issue that is still open, so that everyone who has been discussing this for a long time in London (more than just us) may also find resolution?

**Comment by rebeccaradding** [comment]
Hey everyone - lots to discuss, and I genuinely anticipate a very fruitful conversation.

Please see [my recent comment](https://github.com/foundersandcoders/selection-committee/issues/49#issuecomment-304499296) and indicate when you are free to meet to discuss and plan for the changes we decide on.

**Comment by jsms90** [comment]
@rebeccaradding github comments aren't the best medium for voting or stating preference of options in any way. [Doodle poll](https://doodle.com/poll/iybmtbm7tx95zumu) to the rescue :heart_eyes: 

But please let's go with [these proposed action steps](https://github.com/foundersandcoders/selection-committee/issues/49#issuecomment-304519614)

**Comment by jsms90** [comment]
Proposal to "Update the Application and Selection Process" passed - no more video :tada:
